// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/envoy/service/tap/v3/tap.proto

package tapv3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TapRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TapRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TapRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TapRequestMultiError, or
// nil if none found.
func (m *TapRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TapRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTraceData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TapRequestValidationError{
					field:  "TraceData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TapRequestValidationError{
					field:  "TraceData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTraceData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TapRequestValidationError{
				field:  "TraceData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TapRequestMultiError(errors)
	}

	return nil
}

// TapRequestMultiError is an error wrapping multiple validation errors
// returned by TapRequest.ValidateAll() if the designated constraints aren't met.
type TapRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TapRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TapRequestMultiError) AllErrors() []error { return m }

// TapRequestValidationError is the validation error returned by
// TapRequest.Validate if the designated constraints aren't met.
type TapRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TapRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TapRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TapRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TapRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TapRequestValidationError) ErrorName() string { return "TapRequestValidationError" }

// Error satisfies the builtin error interface
func (e TapRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTapRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TapRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TapRequestValidationError{}

// Validate checks the field values on TapResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TapResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TapResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TapResponseMultiError, or
// nil if none found.
func (m *TapResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TapResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TapResponseMultiError(errors)
	}

	return nil
}

// TapResponseMultiError is an error wrapping multiple validation errors
// returned by TapResponse.ValidateAll() if the designated constraints aren't met.
type TapResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TapResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TapResponseMultiError) AllErrors() []error { return m }

// TapResponseValidationError is the validation error returned by
// TapResponse.Validate if the designated constraints aren't met.
type TapResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TapResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TapResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TapResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TapResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TapResponseValidationError) ErrorName() string { return "TapResponseValidationError" }

// Error satisfies the builtin error interface
func (e TapResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTapResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TapResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TapResponseValidationError{}
